import { Zbiorka } from "./Zbiorka";

export const Akcje = () => {
  return <div id="zbiorki">
    <Zbiorka image={require("../Images/moon.png")} title={"Comic Relief"} text={"W ramach organizowanego co dwa lata show telewizyjnego ta działająca od 1988 r. brytyjska organizacja charytatywna namawia osoby z pierwszych stron gazet do wystąpień w nietypowych dla nich rolach. W ramach dni Czerwonego Nosa aktorzy, politycy i członkowie rodziny królewskiej w oku kamery depilują nogi, farbują włosy, sprzedają ciastka. Wszystko to z nieodłącznym atrybutem w postaci czerwonego nosa, charakterystycznego dla klownów. Dochód z akcji – datki można składać tradycyjnie podczas kwesty jak i za pośrednictwem internetu  – przeznaczany jest dla potrzebujących w Wilkiej Brytanii i Afryce."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"Klauni bez granic"} text={"Amerykańska organizacja z oddziałami w Belgii, Niemczech, Francji, Włochach, Hiszpanii, Irlandii. Zrzesza artystów, którzy występują jako klauni dla dzieci dotkniętych wojną lub klęskami żywiołowymi."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"NajlepszeJestBlisko"} text={"Marka przekazuje za każdy tysiąc zdjęć, 10 tysięcy złotych na Stowarzyszenie Mali Braci Ubogich, która zorganizuje Wigilię dla starszych, samotnych osób.  Na ten moment przesłanych zostało prawie 3 500 zdjęć, a więc zebrania pełnej kwoty 50 000 złotych brakuje już bardzo niewiele!Wszystko, co wystarczy zrobić, aby wesprzeć potrzebujących to przygotować ciasto lub inne słodkości, zrobić im zdjęcie, a następnie dodać na swój profil w mediach społecznościowych lub na stronę najlepszejestblisko.pl z hashtagiem #NajlepszeJestBlisko."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"Poranek z Kawą"} text={"Praktykowana w wielu państwach akcja w ramach której jednego dnia (27.09) przechodnie piją poranną kawę przygotowaną przez fundację Macmillan Cancer Support, a potem płacą za nią wedle uznania. Akcja największym powodzeniem cieszy się w Wielkiej Brytanii w 2012 roku 115 tysięcy ludzi zebrało ponad 15 milionów funtów."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"Podziel się Posiłkiem"} text={"Program społeczny, którego celem jest walka z niedożywieniem dzieci w Polsce. Zainicjowany przez firmę Danone, jako element strategii społecznej odpowiedzialności firmy w 2003 roku. Współorganizatorem programu od 2005 roku jest Fundacja Polsat, a partnerem strategicznym od 2004 roku Banki Żywności. Do tej pory, w wyniku programu, do dzieci trafiło 10 milionów posiłków."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"Układamypomagamy"} text={"Dzieci uwielbiają klocki. Duży sentyment mają do nich także dorośli. Dlatego firma Klocki Blocki postanowiła wykorzystać tę sympatię i zorganizowała akcję opatrzoną hashtagami #układamypomagamy, #KlockiBlocki #FundacjaMamMarzenie. Ten ostatni nie znalazł się tu przypadkiem, bowiem to właśnie na tę fundacje zostaną przekazane pieniądze ze zbiórki."}/>
    <Zbiorka image={require("../Images/moon.png")} title={"Charytatywnachoinka"} text={"Przed Świętami warto również pamiętać o tych, którzy są uznawani za przyjaciela człowieka, czyli psach. Niestety, nie wszystkie z nich spędzą w tym roku ten dzień z kochającym człowiekiem, ponieważ są bezdomne. I to właśnie dla nich Fundacja Sarigato zorganizowała specjalną akcję #charytatywnachoinka."}/>
    </div>
}
