import { Zbiorka } from "./Zbiorka";

export const Zbiorki = () => {
  return <div id="zbiorki">
    <Zbiorka link={"https://www.afm-telethon.fr/en"} image={require("../Images/1.png")} title={"AFM Telethon"} text={"Jeden z najpopularniejszych maratonów telewizyjnych (czyli teletonów) świata nadawany jest we Francji. Organizuje go AFM: organizacja na rzecz walki z miopatią (zwiotczeniem mięśni). Podczas 30 godzin teletonu na wszystkich kanałach francuskiej telewizji publicznej nadawane są informacje i prowadzone dyskusje na temat choroby. W tym czasie trwa też telefoniczna i sms-owa zbiórka pieniędzy. Francuski telethon działa od 1987 roku."}/>
    <Zbiorka link={"https://www.wosp.org.pl"} image={require("../Images/9.png")} title={"Finał Wielkiej Orkiestry Świątecznej Pomocy"} text={"Celem Fundacji jest działalność w zakresie ochrony zdrowia, polegająca na ratowaniu życia chorych osób, w szczególności dzieci, i działanie na rzecz poprawy stanu ich zdrowia, jak również na działaniu na rzecz promocji zdrowia i profilaktyki zdrowotnej."}/>
    <Zbiorka link={"https://www.fundacjapolsat.pl/nasza-historia/"} image={require("../Images/3.png")} title={"Podaruj dzieciom słońce."} text={"Coroczna akcja, której celem jest uzyskanie środków na pomoc chorym dzieciom. Tegoroczna edycja zachęca do udziału hasłem „Twój wybór pomaga chorym dzieciom”. Każdy konsument kupujący w okresie od 1 września do 24."}/>
    <Zbiorka link={"https://fundacja.tvn.pl"} image={require("../Images/4.png")} title={"Fundacja TVN"} text={"Ogólnopolska fundacja, będąca organizacją pozarządową posiadającą także status organizacji pożytku publicznego. Do 2021 działała pod nazwą Fundacja TVN Nie jesteś sam.Fundacja prowadzi działania na rzecz rzeczowego i finansowego wspierania chorych dzieci i osób starszych. Zajmuje się także pomocą na rzecz placówek służby zdrowia i ośrodków pomocy społecznej. Finansuje m.in. remonty oddziałów szpitalnych, turnusy rehabilitacyjnych, zakup protez. W ciągu pierwszych dziesięciu lat działalności na cele charytatywne przekazała kwotę około 140 milionów złotych."}/>
    <Zbiorka link={"https://www.pajacyk.pl"} image={require("../Images/5.jpg")} title={"Pajacyk"} text={"Program dożywiania dzieci w szkołach, który od 1998 roku prowadzi Polska Akcja Humanitarna (PAH). W ramach programu finansowane są posiłki w polskich szkołach i placówkach środowiskowych. Zasięg działania Pajacyka obejmuje także kraje, w których panuje ubóstwo lub toczą się wojny i trwałe konflikty zbrojne takie, jak Somalia czy Sudan Południowy.Dla realizacji programu stworzona została witryna internetowa Polska Strona Głodu. Za jej pomocą można go wesprzeć, klikając w brzuszek pajacyka, co powoduje wyświetlenie strony z reklamami, za co reklamodawcy przekazują na rzecz programu pieniądze."}/>
    <Zbiorka link={"https://www.siepomaga.pl/milion"} image={require("../Images/6.jpg")} title={"Milionnamilion"} text={"Ta akcja również jest stworzona przez markę, z tym, że osobistą. Zorganizowała ją Małgorzata Kożuchowska wraz z Akademią Przyszłości z okazji pierwszego miliona subskrypcji aktorki. Jej celem jest zebranie kwoty miliona złotych dla dzieci z ubogich rodzin, na zakup sprzętu, typu: laptopy, tablety itd. Wszystko po to, aby miały szansę normalnie uczestniczyć w zajęciach online."}/>
    <Zbiorka link={"https://cateromarket.pl/blog/pomocne-pudelko-akcja-spoleczna"} image={require("../Images/7.jpg")} title={"Pomocne Pudełko"} text={"Wciąż w naszym kraju wiele osób nie ma możliwości spożycia pełnowartościowych posiłków. Dlatego też, w takich miastach jak: Warszawa, Kraków i Białystok organizowana jest akcja Pomocne Pudełko. Odpowiada za nią Stowarzyszenie Przedsiębiorców Branży Cateringu Dietetycznego wraz z firmami Cateromarket, Goodspeed i InPost."}/>
    <Zbiorka link={"https://pck.pl/zbiorka-darow-rzeczowych-dla-uchodzcow-z-ukrainy/"} image={require("../Images/10.jpg")} title={"Zbiórka darów dla dzieci z Ukrainy"} text={"W duchu solidarności z Ukrainą- ukraińskimi dziećmi i ich rodzinami wraz ze szpitalem w Kościanie zorganizowaliśmy zbiórkę najpotrzebniejszych artykułów dla dzieci z Ukrainy. Zbieraliśmy mleko w proszku, butelki ze smoczkiem, pieluchy jednorazowe, artykuły higieniczne, słoiczki z jedzeniem, gryzaki, grzechotki, materiały opatrunkowe, koce, śpiwory latarki, baterie.  Zbiórka rozpoczęła się w marcu 2022 i będzie trwała aż do odwołania."}/>
    <Zbiorka link={"http://www.zakretki.info"} image={require("../Images/11.jpg")} title={'Akcja "ZBIÓRKA NAKRĘTEK"'} text={"Od kilku lat w naszym przedszkolu przeprowadzamy zbiórkę plastikowych nakrętek. Akcja ma wiele aspektów. Przede wszystkim jednak uczymy dzieci, że często niewiele trzeba, żeby pomóc drugiemu człowiekowi (nakrętki są przeznaczone na rehabilitację chorych dzieci). Jednocześnie wspieramy ochronę środowiska, bo dzięki takim akcjom o wiele mniej zakręconych butelek trafia na wysypiska śmieci."}/>
    <Zbiorka link={"https://www.zbierajbaterie.pl/aktualnosci"} image={require("../Images/12.jpg")} title={'Akcja "ZBIÓRKA BATERII"'} text={"Dzieci przynoszą zużyte baterie do i wrzucają je do specjalnego pojemnika, który znajduje się w szatni.  Dzięki temu dowiadują się, że zużyte baterie wyrzucane w sposób niekontrolowany stanowią wielkie zagrożenie dla środowiska ponieważ substancje w nich zawarte mogą zanieczyszczać glebę i wodę oraz pośrednio szkodzić zdrowiu człowieka. Poprzez udział w tej akcji dzieci nabywają właściwe nawyki dotyczące ochrony środowiska naturalnego."}/>
  </div>
}
